# Generated by Django 4.0.6 on 2022-07-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
