# Generated by Django 4.0.6 on 2022-07-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cart_date_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_ordered',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered_date',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(blank=True, to='store.order'),
        ),
    ]
